### PR TITLE
USB C firmware for SPIBone

### PR DESCRIPTION
**Pull request by hansfbaier**
Hi, I validated this at 2MHz and SPIBone. 
This works with litex_server in USB mode.
image

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @hansfbaier! Interesting, that's merged.

**Comment by suarezvictor** [comment]
This seems good. Controlling the wishbone or AXI bus from a PC por other USB host seems useful. What's the advantage of using a RP2040 as bridge instead of a UARTbone and a FTDI device? Price?
A valentyUSB based CDC core with a UARTBone will also provide same function without need of a MCU, at the cost of some fabric of course

**Comment by hansfbaier** [comment]
I hoped it would be faster than UART while I really like the convenience of the Pmod form factor of the zero 2040.  Main use case is litescope of course. I can get it to 2MHz currently, maybe 3 are possible.

**Comment by hansfbaier** [comment]
Price is compelling too of course
And the flexibility of those

**Comment by suarezvictor** [comment]
Any advantage of SPi instead of just UART? That would avoid requiring support in litex linux tools.
Interfacing with Pulseview would allow interpretation of protocols, see
https://www.hackster.io/markkomus/using-a-raspberry-pi-pico-as-a-logic-analyzer-with-pulseview-e12543

**Comment by hansfbaier** [comment]
It's possibly faster because synchronyous. I need it for litescope.

**Comment by suarezvictor** [comment]
Thanks Hams, great development

**Pull request merged**
